version: "3.7"
services: 
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    container_name: mongodb
    volumes: 
      - "~/mongo/data:/data/db"
  bot:
    environment:
      - TELEGRAM_TOKEN=1783538770:AAGelOwSDkO0Yjz6nNdaBAmVUcrxIEHvBCA
    image: vswntx/covid-kerala:v0.1-beta.1
    ports:
    - "8080:8080"
    depends_on:
    - mongodb
  watchtower:
    image: containrrr/watchtower 
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30